services:
    maxc.users.admin.user:
        class: Maxc\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }
        arguments:
            - ~
            - Maxc\UserBundle\Entity\User
            - 'MaxcUserBundle:UserAdmin'