services:
    maxc.users.admin.user:
        class: Maxc\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }
        arguments:
            - ~
            - Maxc\UserBundle\Entity\User
            - 'MaxcUserBundle:UserAdmin'

    maxc.registration.form.type:
        class: Maxc\UserBundle\Form\Type\CaptchaRegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: maxc_captcha_registration }